# Generated by Django 5.1.4 on 2024-12-09 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0001_initial'),
        ('propuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='ganador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ganador_de', to='propuestas.propuesta'),
        ),
    ]
