# Generated by Django 5.1.4 on 2024-12-10 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0002_licitacion_ganador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', help_text='Define si la licitación está abierta o cerrada', max_length=10),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que creó la licitación', on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
