# Generated by Django 5.1.4 on 2024-12-17 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0004_alter_licitacion_estado_alter_licitacion_ganador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('especificaciones', models.TextField()),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='gestion_licitaciones.licitacion')),
            ],
        ),
    ]
