# Generated by Django 5.1.4 on 2024-12-17 05:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0006_alter_detallelicitacion_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licitacion',
            name='ganador',
        ),
        migrations.AlterField(
            model_name='detallelicitacion',
            name='especificaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Especificaciones del Equipo'),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
