# Generated by Django 5.1.4 on 2024-12-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0008_licitacion_ganador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del componente, por ejemplo, CPU, Monitor.', max_length=255)),
                ('descripcion', models.TextField(help_text='Descripción o especificaciones del componente.')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad requerida.')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_licitaciones.licitacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
