# Generated by Django 5.1.4 on 2024-12-18 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0009_detallelicitacion_delete_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion_licitaciones.licitacion')),
            ],
        ),
    ]
