# Generated by Django 5.1.4 on 2024-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_licitaciones', '0010_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallelicitacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
